/**
 * Stable business error codes (SCREAMING_SNAKE_CASE) — exposed to the
 * frontend via the global error format `{code,message,details,traceId}`.
 * See `docs/03-tech-lead/coding-standards.md` §7.
 */
export const ERROR_CODES = {
  // Generic
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  INTERNAL_ERROR: 'INTERNAL_ERROR',

  // Auth
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  EMAIL_ALREADY_USED: 'EMAIL_ALREADY_USED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  LINK_EXPIRED: 'LINK_EXPIRED',
  LINK_INVALID: 'LINK_INVALID',
  LINK_ALREADY_USED: 'LINK_ALREADY_USED',
  WEAK_PASSWORD: 'WEAK_PASSWORD',
  ICE_ALREADY_USED: 'ICE_ALREADY_USED',
  SOCIAL_ALREADY_LINKED: 'SOCIAL_ALREADY_LINKED',
  SOCIAL_OAUTH_FAILED: 'SOCIAL_OAUTH_FAILED',

  // Marketplace / business
  PROFILE_INCOMPLETE: 'PROFILE_INCOMPLETE',
  SLOT_FULL: 'SLOT_FULL',
  EXPIRED: 'EXPIRED',
  ALREADY_APPLIED: 'ALREADY_APPLIED',

  // Brand
  BRAND_ALREADY_LINKED: 'BRAND_ALREADY_LINKED',
  BRAND_NOT_FOUND: 'BRAND_NOT_FOUND',

  // Documents
  CIN_ALREADY_VALIDATED: 'CIN_ALREADY_VALIDATED',
  CIN_NOT_FOUND: 'CIN_NOT_FOUND',
  INVALID_TRANSITION: 'INVALID_TRANSITION',
  INVALID_CIN_TRANSITION: 'INVALID_CIN_TRANSITION',
  ICE_NOT_FOUND: 'ICE_NOT_FOUND',
  WRONG_PASSWORD: 'WRONG_PASSWORD',
  PASSWORD_INVALID: 'PASSWORD_INVALID',
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
