export const NOTIFICATION_TYPES = [
  'APPLICATION_ACCEPTED',
  'APPLICATION_REJECTED',
  'BRIEF_RECEIVED',
  'CONTENT_MODIFICATION_REQUESTED',
  'DELIVERABLE_VALIDATED',
  'PAYMENT_RECEIVED',
  'MESSAGE_RECEIVED',
  'CIN_VALIDATED',
  'OPPORTUNITY_EXPIRING',
  'AI_COACH_RECOMMENDATION',
  'APPLICATION_RECEIVED',
  'DELIVERABLE_SUBMITTED',
  'PAYMENT_COMPLETED_OR_FAILED',
  'NEW_BRAND_LINKED',
] as const;
export type NotificationType = (typeof NOTIFICATION_TYPES)[number];
